import { getCategoryEmoji } from '@/lib/utils';

const GRADE_BG: Record<string, string> = {
  'A+': 'text-lime',
  A: 'text-lime',
  'B+': 'text-white',
  B: 'text-white',
  C: 'text-white',
  D: 'text-white',
  F: 'text-white',
};

// Styled shareable report card for WhatsApp sharing
export function ShareCard({
  grade,
  month,
  topCategory,
  savingsRate,
  improvement,
}: {
  grade: string;
  month: string;
  topCategory: string;
  savingsRate: number;
  improvement: string;
}) {
  const monthLabel = new Date(`${month}-01`).toLocaleDateString('en-PK', {
    month: 'long',
    year: 'numeric',
  });

  return (
    <div className="overflow-hidden rounded-3xl bg-sidebar shadow-card">
      <div className="bg-gradient-to-br from-primary/30 to-transparent px-6 py-4">
        <div className="flex items-center justify-between">
          <span className="text-sm font-bold tracking-wide text-lime">HisaabAI</span>
          <span className="text-xs text-white/60">{monthLabel}</span>
        </div>
      </div>

      <div className="px-6 pb-6 pt-2">
        <p className="text-center text-xs uppercase tracking-widest text-white/50">
          Monthly Report Card
        </p>
        <div
          className={`my-4 text-center font-number text-7xl font-bold ${GRADE_BG[grade] || 'text-lime'}`}
        >
          {grade}
        </div>

        <div className="space-y-2 rounded-2xl bg-white/5 p-4 text-sm text-white/80">
          <div className="flex items-center justify-between">
            <span>Top spending</span>
            <span className="font-medium capitalize text-white">
              {getCategoryEmoji(topCategory)} {topCategory}
            </span>
          </div>
          <div className="flex items-center justify-between">
            <span>Savings rate</span>
            <span className="font-number font-semibold text-lime">{savingsRate}%</span>
          </div>
          <div className="flex items-center justify-between">
            <span>vs last month</span>
            <span className="font-medium capitalize text-white">{improvement}</span>
          </div>
        </div>

        <p className="mt-4 text-center text-xs text-white/40">Generated by HisaabAI · hisaabai.vercel.app</p>
      </div>
    </div>
  );
}
